### ISSUE TITLE
Research into how the adminstration tools work (django-auth)

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/Ouroboros#5]
- They have admin panel for adminstrating the event
- I have no idea what that is or how it works

Deliverables (write a comment with these things:
- Some info on the features of the administration tools
   - How do we edit models?
   - How do we accept people?
- How (in the code) are the models structured to add the extra fields?

**Comment by samarthdave** [comment]
# :rocket: Obos Research :scroll:

## :hammer: Models
The ```models.py``` files I found - each has Python subclasses
```
hiss/application/models.py
hiss/user/models.py
hiss/volunteer/models.py
hiss/team/models.py
```

### A summary of the models as classes & their files
```python
from django.db import models
from django.contrib.auth import models as auth_models

# application/models.py
class WaveManager(models.Manager):
class Wave(models.Model):
class School(models.Model):
class Application(models.Model):

# user/models.py
class EmailUserManager(auth_models.UserManager):
class User(auth_models.AbstractUser):

# team/models.py
class Team(models.Model):

# volunteer/models.py
class Event(models.Model):
class FoodEvent(Event):
class WorkshopEvent(Event):
```

###  :zap: Admin Interface
some of the classes above are reflected in the image shown
![image](https://user-images.githubusercontent.com/4997589/83343605-43055700-a2c2-11ea-990c-5e1f1d15bb56.png)

The classes are added to the admin interface through the respective **admin.py** files through the **register** method:

```python
# hiss/application/admin.py
# ...
admin.site.register(Application, ApplicationAdmin)
admin.site.register(Wave, WaveAdmin)
```
```
hiss/application/admin.py
hiss/user/admin.py
hiss/volunteer/admin.py
hiss/team/admin.py
```

### :pencil: Adding/Creating fields
I think [this guide](https://ultimatedjango.com/learn-django/lessons/create-the-model/) is dated but it captures the gist:
1. Create the **models.py** file
2. Run the migration script
```bash
python manage.py makemigrations MODEL_NAME_PLURAL
python manage.py migrate MODEL_NAME_PLURAL
```
3. Register in the admin file for ```/admin``` access (edit, change, etc.)
```python
from django.contrib import admin
from .models import Subscriber

admin.site.register(Subscriber)
```

## :computer: Models within Code
Python seems to have nice built in classes with good helper methods for easy configuration (defaults, data types, etc.) with their ORM
```python
class Application(models.Model): # A "Hacker's" Application

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    datetime_submitted = models.DateTimeField(auto_now_add=True)
    # ...
    first_name = models.CharField(
        max_length=255, blank=False, null=False, verbose_name="first name"
    )
    # ...
    question1 = models.TextField(QUESTION1_TEXT, max_length=500)
```

### :white_check_mark: Accepting applicants

I haven't been able to create new Users (even through the Admin interface) since I'm getting some django errors. But, ```/admin``` let's the admin manually search & filter through applicants to review their submissions.

I imagine there's probably a better way of doing it (the interface is ugly and the process might be slowed down because of it) but it might suffice for now.

Below, you can see the radio field in code & in the admin interface.
```python
status = models.CharField(choices=STATUS_OPTIONS, max_length=1, default=STATUS_PENDING)
```
![image](https://user-images.githubusercontent.com/4997589/83344034-7b5b6400-a2c7-11ea-856e-cdaf7b654cdb.png)
